-- Keep production skill rows on the same exact SVGs as the deterministic seed.

update public.skill as skill
set icon_bucket = '',
    icon_path = source.icon_path,
    icon_path_light = source.icon_path_light,
    updated_at = timezone('utc', now())
from (values
  ('frontend', 'TypeScript', '/skill-icons/frontend-typescript.svg', null),
  ('frontend', 'JavaScript', '/skill-icons/frontend-javascript.svg', null),
  ('frontend', 'React', '/skill-icons/frontend-react.svg', '/skill-icons/frontend-react-light.svg'),
  ('frontend', 'Next.js', '/skill-icons/frontend-next-js.svg', null),
  ('frontend', 'Vue 3', '/skill-icons/frontend-vue-3.svg', null),
  ('frontend', 'Tailwind CSS', '/skill-icons/frontend-tailwind-css.svg', null),
  ('mobile', 'Kotlin', '/skill-icons/mobile-kotlin.svg', null),
  ('mobile', 'Swift', '/skill-icons/mobile-swift.svg', null),
  ('mobile', 'Flutter', '/skill-icons/mobile-flutter.svg', null),
  ('mobile', 'Dart', '/skill-icons/mobile-dart.svg', null),
  ('mobile', 'Android', '/skill-icons/mobile-android.svg', null),
  ('mobile', 'Firebase', '/skill-icons/mobile-firebase.svg', null),
  ('backend', 'Python', '/skill-icons/backend-python.svg', null),
  ('backend', 'Java', '/skill-icons/backend-java.svg', null),
  ('backend', 'C++', '/skill-icons/backend-c-plus-plus.svg', null),
  ('backend', 'C', '/skill-icons/backend-c.svg', null),
  ('backend', 'Bun', '/skill-icons/backend-bun.svg', null),
  ('backend', 'x86 Asm', '/skill-icons/backend-x86-asm.svg', null),
  ('storage', 'Node.js', '/skill-icons/storage-node-js.svg', null),
  ('storage', 'GraphQL', '/skill-icons/storage-graphql.svg', null),
  ('storage', 'PostgreSQL', '/skill-icons/storage-postgresql.svg', null),
  ('storage', 'MySQL', '/skill-icons/storage-mysql.svg', null),
  ('storage', 'MariaDB', '/skill-icons/storage-mariadb.svg', null),
  ('storage', 'SQL', '/skill-icons/storage-sql.svg', null),
  ('devops', 'Docker', '/skill-icons/devops-docker.svg', null),
  ('devops', 'Git', '/skill-icons/devops-git.svg', null),
  ('devops', 'GitHub', '/skill-icons/devops-github.svg', null),
  ('devops', 'CI/CD', '/skill-icons/devops-ci-cd.svg', null),
  ('devops', 'Linux', '/skill-icons/devops-linux.svg', null),
  ('devops', 'Pytest', '/skill-icons/devops-pytest.svg', null),
  ('ai', 'LLM Integration', '/skill-icons/ai-llm-integration.svg', null),
  ('ai', 'Function Calling', '/skill-icons/ai-function-calling.svg', null),
  ('ai', 'Prompt Design', '/skill-icons/ai-prompt-design.svg', null),
  ('ides', 'VS Code', '/skill-icons/ides-vs-code.svg', null),
  ('ides', 'Visual Studio', '/skill-icons/ides-visual-studio.svg', null),
  ('ides', 'Figma', '/skill-icons/ides-figma.svg', null),
  ('ides', 'Bitbucket', '/skill-icons/ides-bitbucket.svg', null),
  ('ides', 'Premiere Pro', '/skill-icons/ides-premiere-pro.svg', null),
  ('workflow', 'Jira', '/skill-icons/workflow-jira.svg', null),
  ('workflow', 'Trello', '/skill-icons/workflow-trello.svg', null),
  ('workflow', 'Cypress', '/skill-icons/workflow-cypress.svg', '/skill-icons/workflow-cypress-light.svg'),
  ('workflow', 'Jenkins', '/skill-icons/workflow-jenkins.svg', null),
  ('workflow', 'Vercel', '/skill-icons/workflow-vercel.svg', null),
  ('workflow', 'Bash', '/skill-icons/workflow-bash.svg', null),
  ('webdata', 'HTML5', '/skill-icons/webdata-html5.svg', null),
  ('webdata', 'CSS3', '/skill-icons/webdata-css3.svg', null),
  ('webdata', 'PHP', '/skill-icons/webdata-php.svg', null),
  ('webdata', 'Flask', '/skill-icons/webdata-flask.svg', null),
  ('webdata', 'Express', '/skill-icons/webdata-express.svg', null),
  ('webdata', 'MongoDB', '/skill-icons/webdata-mongodb.svg', null)
) as source(category, name, icon_path, icon_path_light)
where skill.category = source.category
  and skill.name = source.name;
